### ISSUE TITLE
Consider `apt clean` and `apt autoremove` in docker-apt-install

### ISSUE THREAD

**Issue by sjperkins** [kernsuite-docker/base#1]
https://github.com/crashvb/base-docker#debian-package-deployment

Might save on some more space. Just a thought.

**Comment by gijzelaerr** [comment]
`apt-get autoremove` will remove packages that were installed as dependencies of previous installed and then removed packages.  Since we typically only install packages during a KERN docker image creation this is not really relevant. Or do you think else wise?

**Comment by sjperkins** [comment]
Yes, I can see why `autoremove` might be unnecessary. It might be useful if you want to be `absolutely` sure you've nuked everything ;-)

**Comment by gijzelaerr** [comment]
Probably better to let somebody explicitly decide if he wants to have these dangling dependencies removed. `docker-apt-install` has as goal to install stuff as a one liner and cleaning temp files up, not removing stuff. closing this issue ;)
